### PR TITLE
Button Icons

### PR DESCRIPTION
**Pull request by alustig3**
Added icons (from https://icons.mono.company/) to several buttons in the GUI.

some example screenshots below: 
Screen Shot 2020-09-29 at 12 52 43 PM
Screen Shot 2020-09-29 at 12 52 30 PM
Screen Shot 2020-09-29 at 12 52 59 PM

### CODE REVIEW

**Comment by ThomasAkam** [comment]
Thanks for putting in this pull request, the icons look like a nice addition.  I am a bit swamped right now with other work but hope to have time over the next month of so for pyControl dev work so will look at integrating this then.

**Comment by alustig3** [comment]
Sounds good!

**Comment by ThomasAkam** [comment]
Gave the icons a try and really like them.  I just pushed a couple of small modifications, take a look and let me know if your happy with them.  If so I'll merge with the dev branch.

**Comment by alustig3** [comment]
Looks good to me 👍

**Pull request merged**
